#! /usr/bin/env python

# Form implementation generated from reading ui file 'Robot_Control.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from Window2 import Load_Program_Window
from dashboard_dual_service_2 import Dashboard_Client
import rospy
from std_srvs.srv import Trigger, TriggerRequest
from ur_dashboard_msgs.srv import Load, LoadRequest, Popup, PopupRequest, IsInRemoteControl,IsInRemoteControlRequest, GetRobotMode, GetRobotModeRequest, IsProgramRunning, IsProgramRunningRequest


class Ui_RobotControl(object):
    def __init__(self):
        self.p_robot = Dashboard_Client('play', Trigger, TriggerRequest(), 'p')
        self.d_robot = Dashboard_Client('play', Trigger, TriggerRequest(), 'd')
        self.virtual_robot = Dashboard_Client('play', Trigger, TriggerRequest(), '')

    def load_program_window(self):
        '''Information derived from if __name__ == main in Window2.py
           - type of window that required to be open
           - ui to be opened = class of the python file of the UI. This is the object name of the winodw
           - get all the ui setup of the second window
           - show the ui
        '''
        self.window = QtWidgets.QMainWindow()
        self.ui = Load_Program_Window()
        self.ui.setupUi(self.window)
        self.window.show()

    def power_on_robot(self, robot_name):
        power_on = Dashboard_Client('power_on', Trigger, TriggerRequest(), robot_name)
        brake_release = Dashboard_Client('brake_release', Trigger, TriggerRequest(), robot_name)
        power_on.call_service()
        brake_release.call_service()

    def stop_program(self, robot_name):
        stop = Dashboard_Client('stop', Trigger, TriggerRequest(), robot_name)
        stop.call_service()

    def pause_program(self, robot_name):
        pause = Dashboard_Client('pause', Trigger, TriggerRequest(), robot_name)
        pause.call_service()


    def play_robot(self, robot_name):
        if robot_name.lower() =='p':
            self.p_robot.play()
        elif robot_name.lower() == 'd':
            self.d_robot.play()
        elif robot_name =='':
            self.virtual_robot.play()
        
    def program_state(self, robot_name):
        program =  Dashboard_Client('power_on', Trigger, TriggerRequest(), robot_name)
        program.program_running()#
    
    def setupUi(self, RobotControl):
        RobotControl.setObjectName("RobotControl")
        RobotControl.resize(2297, 1397)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/robot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RobotControl.setWindowIcon(icon)
        RobotControl.setStyleSheet("QWidget{\n"
"background-color:rgb(52, 52, 52)\n"
"}\n"
"QGraphicsView{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"QCheckBox{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"QLabel{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"QPushButton{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"QPushButton Emergency{\n"
"background-color:rgb(255, 0, 0)\n"
"}\n"
"QTextBrowser{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"QLineEdit{\n"
"background-color:rgb(205, 205, 205)\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(RobotControl)
        self.centralwidget.setObjectName("centralwidget")
        self.Top_Bar = QtWidgets.QGraphicsView(self.centralwidget)
        self.Top_Bar.setGeometry(QtCore.QRect(0, 0, 2201, 51))
        brush = QtGui.QBrush(QtGui.QColor(255, 85, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.Top_Bar.setBackgroundBrush(brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.Top_Bar.setForegroundBrush(brush)
        self.Top_Bar.setInteractive(True)
        self.Top_Bar.setObjectName("Top_Bar")
        self.SkyshipsLogo = QtWidgets.QLabel(self.centralwidget)
        self.SkyshipsLogo.setGeometry(QtCore.QRect(10, 1, 91, 41))
        self.SkyshipsLogo.setText("")
        self.SkyshipsLogo.setPixmap(QtGui.QPixmap(":/Photos/Images/logo.png"))
        self.SkyshipsLogo.setScaledContents(True)
        self.SkyshipsLogo.setObjectName("SkyshipsLogo")
        self.LoadScript = QtWidgets.QPushButton(self.centralwidget)
        self.LoadScript.setGeometry(QtCore.QRect(1880, 10, 101, 31))
        self.LoadScript.setObjectName("LoadScript")
        self.Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(1990, 10, 101, 31))
        self.Settings.setObjectName("Settings")
        self.Help = QtWidgets.QPushButton(self.centralwidget)
        self.Help.setGeometry(QtCore.QRect(2100, 10, 91, 31))
        self.Help.setObjectName("Help")
        self.Button_Bar = QtWidgets.QGraphicsView(self.centralwidget)
        self.Button_Bar.setGeometry(QtCore.QRect(0, 30, 2201, 1331))
        self.Button_Bar.setObjectName("Button_Bar")
        self.Robot2Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Robot2Connect.setGeometry(QtCore.QRect(230, 110, 40, 40))
        self.Robot2Connect.setStyleSheet("background-color: rgb(205, 205, 205)")
        self.Robot2Connect.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/power_off.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/power_on.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Robot2Connect.setIcon(icon1)
        self.Robot2Connect.setIconSize(QtCore.QSize(40, 40))
        self.Robot2Connect.setFlat(True)
        self.Robot2Connect.setObjectName("Robot2Connect")
        self.TaskBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.TaskBox.setGeometry(QtCore.QRect(10, 330, 291, 1011))
        self.TaskBox.setObjectName("TaskBox")
        self.Script_Output = QtWidgets.QGraphicsView(self.centralwidget)
        self.Script_Output.setGeometry(QtCore.QRect(310, 970, 1481, 371))
        self.Script_Output.setObjectName("Script_Output")
        self.ScriptOutput = QtWidgets.QLabel(self.centralwidget)
        self.ScriptOutput.setGeometry(QtCore.QRect(330, 970, 161, 31))
        self.ScriptOutput.setObjectName("ScriptOutput")
        self.TaskLabel = QtWidgets.QLabel(self.centralwidget)
        self.TaskLabel.setGeometry(QtCore.QRect(110, 340, 101, 31))
        self.TaskLabel.setObjectName("TaskLabel")
        self.Positions_2 = QtWidgets.QLabel(self.centralwidget)
        self.Positions_2.setGeometry(QtCore.QRect(1930, 360, 131, 31))
        self.Positions_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Positions_2.setObjectName("Positions_2")
        self.Back2 = QtWidgets.QPushButton(self.centralwidget)
        self.Back2.setGeometry(QtCore.QRect(1435, 50, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Back2.setFont(font)
        self.Back2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/back2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Back2.setIcon(icon2)
        self.Back2.setIconSize(QtCore.QSize(50, 50))
        self.Back2.setFlat(True)
        self.Back2.setObjectName("Back2")
        self.Emergency = QtWidgets.QPushButton(self.centralwidget)
        self.Emergency.setGeometry(QtCore.QRect(1890, 70, 231, 211))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Emergency.setFont(font)
        self.Emergency.setAutoFillBackground(False)
        self.Emergency.setStyleSheet("background-color: rgb(205, 205, 205)")
        self.Emergency.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Emergency.setIcon(icon3)
        self.Emergency.setIconSize(QtCore.QSize(200, 200))
        self.Emergency.setFlat(True)
        self.Emergency.setObjectName("Emergency")
        self.ScriptBox_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.ScriptBox_2.setGeometry(QtCore.QRect(1800, 970, 401, 371))
        self.ScriptBox_2.setStyleSheet("")
        self.ScriptBox_2.setLineWidth(0)
        self.ScriptBox_2.setOpenExternalLinks(True)
        self.ScriptBox_2.setObjectName("ScriptBox_2")
        self.OutputBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.OutputBox.setGeometry(QtCore.QRect(330, 360, 1431, 581))
        self.OutputBox.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.OutputBox.setObjectName("OutputBox")
        self.ScriptBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.ScriptBox.setGeometry(QtCore.QRect(330, 1000, 1441, 321))
        self.ScriptBox.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ScriptBox.setObjectName("ScriptBox")
        self.Play2 = QtWidgets.QPushButton(self.centralwidget)
        self.Play2.setGeometry(QtCore.QRect(1430, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Play2.setFont(font)
        self.Play2.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Play2.setIcon(icon4)
        self.Play2.setIconSize(QtCore.QSize(50, 50))
        self.Play2.setCheckable(True)
        self.Play2.setFlat(True)
        self.Play2.setObjectName("Play2")
        self.Restart2 = QtWidgets.QPushButton(self.centralwidget)
        self.Restart2.setGeometry(QtCore.QRect(1565, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Restart2.setFont(font)
        self.Restart2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Restart.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Restart2.setIcon(icon5)
        self.Restart2.setIconSize(QtCore.QSize(50, 50))
        self.Restart2.setFlat(True)
        self.Restart2.setObjectName("Restart2")
        self.Pause2 = QtWidgets.QPushButton(self.centralwidget)
        self.Pause2.setGeometry(QtCore.QRect(1495, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Pause2.setFont(font)
        self.Pause2.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Pause2.setIcon(icon6)
        self.Pause2.setIconSize(QtCore.QSize(50, 50))
        self.Pause2.setCheckable(True)
        self.Pause2.setFlat(True)
        self.Pause2.setObjectName("Pause2")
        self.Connected1 = QtWidgets.QPushButton(self.centralwidget)
        self.Connected1.setGeometry(QtCore.QRect(50, 60, 171, 41))
        self.Connected1.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.Connected1.setObjectName("Connected1")
        self.Connected2 = QtWidgets.QPushButton(self.centralwidget)
        self.Connected2.setGeometry(QtCore.QRect(50, 110, 171, 41))
        self.Connected2.setStyleSheet("background-color:rgb(170, 255, 127)")
        self.Connected2.setObjectName("Connected2")
        self.UpPosition = QtWidgets.QSlider(self.centralwidget)
        self.UpPosition.setGeometry(QtCore.QRect(2140, 680, 31, 221))
        self.UpPosition.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.UpPosition.setMinimum(0)
        self.UpPosition.setMaximum(100)
        self.UpPosition.setPageStep(1)
        self.UpPosition.setSliderPosition(69)
        self.UpPosition.setOrientation(QtCore.Qt.Vertical)
        self.UpPosition.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.UpPosition.setObjectName("UpPosition")
        self.SidePosition = QtWidgets.QSlider(self.centralwidget)
        self.SidePosition.setGeometry(QtCore.QRect(1840, 900, 311, 31))
        self.SidePosition.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.SidePosition.setMinimum(0)
        self.SidePosition.setMaximum(100)
        self.SidePosition.setPageStep(1)
        self.SidePosition.setOrientation(QtCore.Qt.Horizontal)
        self.SidePosition.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.SidePosition.setObjectName("SidePosition")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 230, 291, 61))
        self.progressBar.setStyleSheet("color: white;")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(1970, 740, 211, 201))
        self.dial.setMaximum(100)
        self.dial.setWrapping(False)
        self.dial.setNotchesVisible(True)
        self.dial.setObjectName("dial")
        self.YBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.YBox.setGeometry(QtCore.QRect(1880, 430, 121, 31))
        self.YBox.setStyleSheet("background-color: white")
        self.YBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.YBox.setObjectName("YBox")
        self.XAxis = QtWidgets.QLabel(self.centralwidget)
        self.XAxis.setGeometry(QtCore.QRect(1840, 390, 31, 31))
        self.XAxis.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.XAxis.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.XAxis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.XAxis.setObjectName("XAxis")
        self.DisconnectedCamera = QtWidgets.QPushButton(self.centralwidget)
        self.DisconnectedCamera.setGeometry(QtCore.QRect(50, 160, 171, 41))
        self.DisconnectedCamera.setStyleSheet("background-color:rgb(255, 0, 0)")
        self.DisconnectedCamera.setObjectName("DisconnectedCamera")
        self.Robot1Connect = QtWidgets.QPushButton(self.centralwidget)
        self.Robot1Connect.setGeometry(QtCore.QRect(230, 60, 40, 40))
        self.Robot1Connect.setStyleSheet("background-color: rgb(205, 205, 205)")
        self.Robot1Connect.setText("")
        self.Robot1Connect.setIcon(icon1)
        self.Robot1Connect.setIconSize(QtCore.QSize(40, 40))
        self.Robot1Connect.setFlat(True)
        self.Robot1Connect.setObjectName("Robot1Connect")
        self.CameraConnect = QtWidgets.QPushButton(self.centralwidget)
        self.CameraConnect.setGeometry(QtCore.QRect(230, 160, 40, 40))
        self.CameraConnect.setStyleSheet("")
        self.CameraConnect.setText("")
        self.CameraConnect.setIcon(icon1)
        self.CameraConnect.setIconSize(QtCore.QSize(40, 40))
        self.CameraConnect.setFlat(True)
        self.CameraConnect.setObjectName("CameraConnect")
        self.Pause1 = QtWidgets.QPushButton(self.centralwidget)
        self.Pause1.setGeometry(QtCore.QRect(645, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Pause1.setFont(font)
        self.Pause1.setText("")
        self.Pause1.setIcon(icon6)
        self.Pause1.setIconSize(QtCore.QSize(50, 50))
        self.Pause1.setCheckable(True)
        self.Pause1.setFlat(True)
        self.Pause1.setObjectName("Pause1")
        self.Play1 = QtWidgets.QPushButton(self.centralwidget)
        self.Play1.setGeometry(QtCore.QRect(580, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Play1.setFont(font)
        self.Play1.setText("")
        self.Play1.setIcon(icon4)
        self.Play1.setIconSize(QtCore.QSize(50, 50))
        self.Play1.setCheckable(True)
        self.Play1.setFlat(True)
        self.Play1.setObjectName("Play1")
        self.Restart1 = QtWidgets.QPushButton(self.centralwidget)
        self.Restart1.setGeometry(QtCore.QRect(715, 240, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Restart1.setFont(font)
        self.Restart1.setText("")
        self.Restart1.setIcon(icon5)
        self.Restart1.setIconSize(QtCore.QSize(50, 50))
        self.Restart1.setFlat(True)
        self.Restart1.setObjectName("Restart1")
        self.Back1 = QtWidgets.QPushButton(self.centralwidget)
        self.Back1.setGeometry(QtCore.QRect(570, 50, 51, 51))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Back1.setFont(font)
        self.Back1.setText("")
        self.Back1.setIcon(icon2)
        self.Back1.setIconSize(QtCore.QSize(50, 50))
        self.Back1.setFlat(True)
        self.Back1.setObjectName("Back1")
        self.ZBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.ZBox.setGeometry(QtCore.QRect(1880, 470, 121, 31))
        self.ZBox.setStyleSheet("background-color: white")
        self.ZBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ZBox.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ZBox.setObjectName("ZBox")
        self.XBox = QtWidgets.QTextBrowser(self.centralwidget)
        self.XBox.setGeometry(QtCore.QRect(1880, 390, 121, 31))
        self.XBox.setStyleSheet("background-color: white")
        self.XBox.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.XBox.setObjectName("XBox")
        self.YAxis = QtWidgets.QLabel(self.centralwidget)
        self.YAxis.setGeometry(QtCore.QRect(1840, 430, 31, 31))
        self.YAxis.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.YAxis.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.YAxis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.YAxis.setObjectName("YAxis")
        self.ZAxis = QtWidgets.QLabel(self.centralwidget)
        self.ZAxis.setGeometry(QtCore.QRect(1840, 470, 31, 31))
        self.ZAxis.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ZAxis.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.ZAxis.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ZAxis.setObjectName("ZAxis")
        self.SwapRobot = QtWidgets.QPushButton(self.centralwidget)
        self.SwapRobot.setGeometry(QtCore.QRect(50, 730, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.SwapRobot.setFont(font)
        self.SwapRobot.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/switch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SwapRobot.setIcon(icon7)
        self.SwapRobot.setIconSize(QtCore.QSize(70, 70))
        self.SwapRobot.setFlat(True)
        self.SwapRobot.setObjectName("SwapRobot")
        self.XAxis_2 = QtWidgets.QLabel(self.centralwidget)
        self.XAxis_2.setGeometry(QtCore.QRect(1822, 900, 16, 31))
        self.XAxis_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.XAxis_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.XAxis_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.XAxis_2.setObjectName("XAxis_2")
        self.YAxis_2 = QtWidgets.QLabel(self.centralwidget)
        self.YAxis_2.setGeometry(QtCore.QRect(2150, 650, 21, 31))
        self.YAxis_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.YAxis_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.YAxis_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.YAxis_2.setObjectName("YAxis_2")
        self.PositionBox = QtWidgets.QGraphicsView(self.centralwidget)
        self.PositionBox.setGeometry(QtCore.QRect(1820, 350, 361, 591))
        self.PositionBox.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.PositionBox.setObjectName("PositionBox")
        self.TaskBox_2 = QtWidgets.QGraphicsView(self.centralwidget)
        self.TaskBox_2.setGeometry(QtCore.QRect(30, 370, 251, 951))
        self.TaskBox_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.TaskBox_2.setObjectName("TaskBox_2")
        self.CameraOutput = QtWidgets.QGraphicsView(self.centralwidget)
        self.CameraOutput.setGeometry(QtCore.QRect(810, 100, 581, 211))
        self.CameraOutput.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.CameraOutput.setObjectName("CameraOutput")
        self.CameraTitle = QtWidgets.QLabel(self.centralwidget)
        self.CameraTitle.setGeometry(QtCore.QRect(1010, 60, 181, 31))
        self.CameraTitle.setObjectName("CameraTitle")
        self.thermal = QtWidgets.QPushButton(self.centralwidget)
        self.thermal.setGeometry(QtCore.QRect(50, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.thermal.setFont(font)
        self.thermal.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/Pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.thermal.setIcon(icon8)
        self.thermal.setIconSize(QtCore.QSize(70, 70))
        self.thermal.setCheckable(True)
        self.thermal.setFlat(True)
        self.thermal.setObjectName("thermal")
        self.Assembly = QtWidgets.QPushButton(self.centralwidget)
        self.Assembly.setGeometry(QtCore.QRect(170, 380, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Assembly.setFont(font)
        self.Assembly.setText("")
        self.Assembly.setIcon(icon8)
        self.Assembly.setIconSize(QtCore.QSize(70, 70))
        self.Assembly.setCheckable(True)
        self.Assembly.setFlat(True)
        self.Assembly.setObjectName("Assembly")
        self.ThermalPaste = QtWidgets.QLabel(self.centralwidget)
        self.ThermalPaste.setGeometry(QtCore.QRect(40, 460, 101, 21))
        self.ThermalPaste.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ThermalPaste.setObjectName("ThermalPaste")
        self.Assembly_2 = QtWidgets.QLabel(self.centralwidget)
        self.Assembly_2.setGeometry(QtCore.QRect(170, 460, 101, 21))
        self.Assembly_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Assembly_2.setObjectName("Assembly_2")
        self.Off2 = QtWidgets.QPushButton(self.centralwidget)
        self.Off2.setEnabled(False)
        self.Off2.setGeometry(QtCore.QRect(250, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off2.setFont(font)
        self.Off2.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/red_circle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/red_circle.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon9.addPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/green_circle.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        self.Off2.setIcon(icon9)
        self.Off2.setIconSize(QtCore.QSize(25, 25))
        self.Off2.setFlat(True)
        self.Off2.setObjectName("Off2")
        self.Off1 = QtWidgets.QPushButton(self.centralwidget)
        self.Off1.setEnabled(False)
        self.Off1.setGeometry(QtCore.QRect(130, 380, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off1.setFont(font)
        self.Off1.setText("")
        self.Off1.setIcon(icon9)
        self.Off1.setIconSize(QtCore.QSize(25, 25))
        self.Off1.setFlat(True)
        self.Off1.setObjectName("Off1")
        self.Dissemble = QtWidgets.QPushButton(self.centralwidget)
        self.Dissemble.setGeometry(QtCore.QRect(170, 500, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Dissemble.setFont(font)
        self.Dissemble.setText("")
        self.Dissemble.setIcon(icon8)
        self.Dissemble.setIconSize(QtCore.QSize(70, 70))
        self.Dissemble.setCheckable(True)
        self.Dissemble.setFlat(True)
        self.Dissemble.setObjectName("Dissemble")
        self.Off3 = QtWidgets.QPushButton(self.centralwidget)
        self.Off3.setEnabled(False)
        self.Off3.setGeometry(QtCore.QRect(130, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off3.setFont(font)
        self.Off3.setText("")
        self.Off3.setIcon(icon9)
        self.Off3.setIconSize(QtCore.QSize(25, 25))
        self.Off3.setFlat(True)
        self.Off3.setObjectName("Off3")
        self.Off4 = QtWidgets.QPushButton(self.centralwidget)
        self.Off4.setEnabled(False)
        self.Off4.setGeometry(QtCore.QRect(250, 500, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off4.setFont(font)
        self.Off4.setText("")
        self.Off4.setIcon(icon9)
        self.Off4.setIconSize(QtCore.QSize(25, 25))
        self.Off4.setFlat(True)
        self.Off4.setObjectName("Off4")
        self.CameraCheck = QtWidgets.QPushButton(self.centralwidget)
        self.CameraCheck.setGeometry(QtCore.QRect(50, 500, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.CameraCheck.setFont(font)
        self.CameraCheck.setText("")
        self.CameraCheck.setIcon(icon8)
        self.CameraCheck.setIconSize(QtCore.QSize(70, 70))
        self.CameraCheck.setCheckable(True)
        self.CameraCheck.setFlat(True)
        self.CameraCheck.setObjectName("CameraCheck")
        self.CameraCheck_2 = QtWidgets.QLabel(self.centralwidget)
        self.CameraCheck_2.setGeometry(QtCore.QRect(40, 580, 101, 21))
        self.CameraCheck_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.CameraCheck_2.setObjectName("CameraCheck_2")
        self.Dissemble_2 = QtWidgets.QLabel(self.centralwidget)
        self.Dissemble_2.setGeometry(QtCore.QRect(180, 580, 71, 21))
        self.Dissemble_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Dissemble_2.setObjectName("Dissemble_2")
        self.ScrewOut = QtWidgets.QPushButton(self.centralwidget)
        self.ScrewOut.setGeometry(QtCore.QRect(170, 610, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.ScrewOut.setFont(font)
        self.ScrewOut.setText("")
        self.ScrewOut.setIcon(icon8)
        self.ScrewOut.setIconSize(QtCore.QSize(70, 70))
        self.ScrewOut.setCheckable(True)
        self.ScrewOut.setFlat(True)
        self.ScrewOut.setObjectName("ScrewOut")
        self.On5 = QtWidgets.QPushButton(self.centralwidget)
        self.On5.setEnabled(False)
        self.On5.setGeometry(QtCore.QRect(130, 610, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.On5.setFont(font)
        self.On5.setText("")
        self.On5.setIcon(icon9)
        self.On5.setIconSize(QtCore.QSize(25, 25))
        self.On5.setFlat(True)
        self.On5.setObjectName("On5")
        self.Off6 = QtWidgets.QPushButton(self.centralwidget)
        self.Off6.setEnabled(False)
        self.Off6.setGeometry(QtCore.QRect(250, 610, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off6.setFont(font)
        self.Off6.setText("")
        self.Off6.setIcon(icon9)
        self.Off6.setIconSize(QtCore.QSize(25, 25))
        self.Off6.setFlat(True)
        self.Off6.setObjectName("Off6")
        self.Empty9_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty9_2.setGeometry(QtCore.QRect(190, 1280, 51, 21))
        self.Empty9_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty9_2.setObjectName("Empty9_2")
        self.ScrewIn = QtWidgets.QPushButton(self.centralwidget)
        self.ScrewIn.setGeometry(QtCore.QRect(50, 610, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.ScrewIn.setFont(font)
        self.ScrewIn.setText("")
        self.ScrewIn.setIcon(icon8)
        self.ScrewIn.setIconSize(QtCore.QSize(70, 70))
        self.ScrewIn.setCheckable(True)
        self.ScrewIn.setFlat(True)
        self.ScrewIn.setObjectName("ScrewIn")
        self.LoadedScript = QtWidgets.QLabel(self.centralwidget)
        self.LoadedScript.setGeometry(QtCore.QRect(170, 810, 91, 21))
        self.LoadedScript.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.LoadedScript.setObjectName("LoadedScript")
        self.ScrewIn_2 = QtWidgets.QLabel(self.centralwidget)
        self.ScrewIn_2.setGeometry(QtCore.QRect(60, 690, 101, 21))
        self.ScrewIn_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ScrewIn_2.setObjectName("ScrewIn_2")
        self.LoadedScript_2 = QtWidgets.QPushButton(self.centralwidget)
        self.LoadedScript_2.setGeometry(QtCore.QRect(170, 730, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.LoadedScript_2.setFont(font)
        self.LoadedScript_2.setText("")
        self.LoadedScript_2.setIcon(icon8)
        self.LoadedScript_2.setIconSize(QtCore.QSize(70, 70))
        self.LoadedScript_2.setCheckable(True)
        self.LoadedScript_2.setFlat(True)
        self.LoadedScript_2.setObjectName("LoadedScript_2")
        self.Off16 = QtWidgets.QPushButton(self.centralwidget)
        self.Off16.setEnabled(False)
        self.Off16.setGeometry(QtCore.QRect(240, 1210, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off16.setFont(font)
        self.Off16.setText("")
        self.Off16.setIcon(icon9)
        self.Off16.setIconSize(QtCore.QSize(25, 25))
        self.Off16.setFlat(True)
        self.Off16.setObjectName("Off16")
        self.Off8 = QtWidgets.QPushButton(self.centralwidget)
        self.Off8.setEnabled(False)
        self.Off8.setGeometry(QtCore.QRect(250, 730, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off8.setFont(font)
        self.Off8.setText("")
        self.Off8.setIcon(icon9)
        self.Off8.setIconSize(QtCore.QSize(25, 25))
        self.Off8.setFlat(True)
        self.Off8.setObjectName("Off8")
        self.Empty9 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty9.setGeometry(QtCore.QRect(160, 1200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty9.setFont(font)
        self.Empty9.setText("")
        self.Empty9.setIcon(icon8)
        self.Empty9.setIconSize(QtCore.QSize(70, 70))
        self.Empty9.setCheckable(True)
        self.Empty9.setFlat(True)
        self.Empty9.setObjectName("Empty9")
        self.ScrewOut_2 = QtWidgets.QLabel(self.centralwidget)
        self.ScrewOut_2.setGeometry(QtCore.QRect(170, 690, 101, 21))
        self.ScrewOut_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ScrewOut_2.setObjectName("ScrewOut_2")
        self.Off10 = QtWidgets.QPushButton(self.centralwidget)
        self.Off10.setEnabled(False)
        self.Off10.setGeometry(QtCore.QRect(250, 850, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off10.setFont(font)
        self.Off10.setText("")
        self.Off10.setIcon(icon9)
        self.Off10.setIconSize(QtCore.QSize(25, 25))
        self.Off10.setFlat(True)
        self.Off10.setObjectName("Off10")
        self.Empty8_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty8_2.setGeometry(QtCore.QRect(70, 1280, 51, 21))
        self.Empty8_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty8_2.setObjectName("Empty8_2")
        self.Off12 = QtWidgets.QPushButton(self.centralwidget)
        self.Off12.setEnabled(False)
        self.Off12.setGeometry(QtCore.QRect(250, 970, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off12.setFont(font)
        self.Off12.setText("")
        self.Off12.setIcon(icon9)
        self.Off12.setIconSize(QtCore.QSize(25, 25))
        self.Off12.setFlat(True)
        self.Off12.setObjectName("Off12")
        self.Off13 = QtWidgets.QPushButton(self.centralwidget)
        self.Off13.setEnabled(False)
        self.Off13.setGeometry(QtCore.QRect(130, 1080, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off13.setFont(font)
        self.Off13.setText("")
        self.Off13.setIcon(icon9)
        self.Off13.setIconSize(QtCore.QSize(25, 25))
        self.Off13.setFlat(True)
        self.Off13.setObjectName("Off13")
        self.Empty7 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty7.setGeometry(QtCore.QRect(170, 1080, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty7.setFont(font)
        self.Empty7.setText("")
        self.Empty7.setIcon(icon8)
        self.Empty7.setIconSize(QtCore.QSize(70, 70))
        self.Empty7.setCheckable(True)
        self.Empty7.setFlat(True)
        self.Empty7.setObjectName("Empty7")
        self.SwapRobot_2 = QtWidgets.QLabel(self.centralwidget)
        self.SwapRobot_2.setGeometry(QtCore.QRect(60, 800, 81, 31))
        self.SwapRobot_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.SwapRobot_2.setLineWidth(-11)
        self.SwapRobot_2.setMidLineWidth(-10)
        self.SwapRobot_2.setScaledContents(False)
        self.SwapRobot_2.setWordWrap(False)
        self.SwapRobot_2.setIndent(-2)
        self.SwapRobot_2.setObjectName("SwapRobot_2")
        self.Empty4 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty4.setGeometry(QtCore.QRect(50, 970, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty4.setFont(font)
        self.Empty4.setText("")
        self.Empty4.setIcon(icon8)
        self.Empty4.setIconSize(QtCore.QSize(70, 70))
        self.Empty4.setCheckable(True)
        self.Empty4.setFlat(True)
        self.Empty4.setObjectName("Empty4")
        self.Empty6_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty6_2.setGeometry(QtCore.QRect(70, 1160, 51, 21))
        self.Empty6_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty6_2.setObjectName("Empty6_2")
        self.Off11 = QtWidgets.QPushButton(self.centralwidget)
        self.Off11.setEnabled(False)
        self.Off11.setGeometry(QtCore.QRect(130, 970, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off11.setFont(font)
        self.Off11.setText("")
        self.Off11.setIcon(icon9)
        self.Off11.setIconSize(QtCore.QSize(25, 25))
        self.Off11.setFlat(True)
        self.Off11.setObjectName("Off11")
        self.CameraScreen = QtWidgets.QLabel(self.centralwidget)
        self.CameraScreen.setGeometry(QtCore.QRect(60, 920, 91, 51))
        self.CameraScreen.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.CameraScreen.setObjectName("CameraScreen")
        self.Empty3_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty3_2.setGeometry(QtCore.QRect(190, 930, 51, 21))
        self.Empty3_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty3_2.setObjectName("Empty3_2")
        self.Off15 = QtWidgets.QPushButton(self.centralwidget)
        self.Off15.setEnabled(False)
        self.Off15.setGeometry(QtCore.QRect(130, 1200, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off15.setFont(font)
        self.Off15.setText("")
        self.Off15.setIcon(icon9)
        self.Off15.setIconSize(QtCore.QSize(25, 25))
        self.Off15.setFlat(True)
        self.Off15.setObjectName("Off15")
        self.Empty3 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty3.setGeometry(QtCore.QRect(170, 850, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty3.setFont(font)
        self.Empty3.setText("")
        self.Empty3.setIcon(icon8)
        self.Empty3.setIconSize(QtCore.QSize(70, 70))
        self.Empty3.setCheckable(True)
        self.Empty3.setFlat(True)
        self.Empty3.setObjectName("Empty3")
        self.Empty5 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty5.setGeometry(QtCore.QRect(170, 970, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty5.setFont(font)
        self.Empty5.setText("")
        self.Empty5.setIcon(icon8)
        self.Empty5.setIconSize(QtCore.QSize(70, 70))
        self.Empty5.setCheckable(True)
        self.Empty5.setFlat(True)
        self.Empty5.setObjectName("Empty5")
        self.Empty8 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty8.setGeometry(QtCore.QRect(50, 1200, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty8.setFont(font)
        self.Empty8.setText("")
        self.Empty8.setIcon(icon8)
        self.Empty8.setIconSize(QtCore.QSize(70, 70))
        self.Empty8.setCheckable(True)
        self.Empty8.setFlat(True)
        self.Empty8.setObjectName("Empty8")
        self.Empty5_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty5_2.setGeometry(QtCore.QRect(190, 1050, 51, 21))
        self.Empty5_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty5_2.setObjectName("Empty5_2")
        self.Off14 = QtWidgets.QPushButton(self.centralwidget)
        self.Off14.setEnabled(False)
        self.Off14.setGeometry(QtCore.QRect(250, 1080, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off14.setFont(font)
        self.Off14.setText("")
        self.Off14.setIcon(icon9)
        self.Off14.setIconSize(QtCore.QSize(25, 25))
        self.Off14.setFlat(True)
        self.Off14.setObjectName("Off14")
        self.Empty7_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty7_2.setGeometry(QtCore.QRect(190, 1160, 51, 21))
        self.Empty7_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty7_2.setObjectName("Empty7_2")
        self.Empty4_2 = QtWidgets.QLabel(self.centralwidget)
        self.Empty4_2.setGeometry(QtCore.QRect(70, 1050, 51, 21))
        self.Empty4_2.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.Empty4_2.setObjectName("Empty4_2")
        self.Off7 = QtWidgets.QPushButton(self.centralwidget)
        self.Off7.setEnabled(False)
        self.Off7.setGeometry(QtCore.QRect(140, 730, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off7.setFont(font)
        self.Off7.setText("")
        self.Off7.setIcon(icon9)
        self.Off7.setIconSize(QtCore.QSize(25, 25))
        self.Off7.setFlat(True)
        self.Off7.setObjectName("Off7")
        self.Empty6 = QtWidgets.QPushButton(self.centralwidget)
        self.Empty6.setGeometry(QtCore.QRect(50, 1080, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Empty6.setFont(font)
        self.Empty6.setText("")
        self.Empty6.setIcon(icon8)
        self.Empty6.setIconSize(QtCore.QSize(70, 70))
        self.Empty6.setCheckable(True)
        self.Empty6.setFlat(True)
        self.Empty6.setObjectName("Empty6")
        self.Off9 = QtWidgets.QPushButton(self.centralwidget)
        self.Off9.setEnabled(False)
        self.Off9.setGeometry(QtCore.QRect(130, 850, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.Off9.setFont(font)
        self.Off9.setText("")
        self.Off9.setIcon(icon9)
        self.Off9.setIconSize(QtCore.QSize(25, 25))
        self.Off9.setFlat(True)
        self.Off9.setObjectName("Off9")
        self.OffGo = QtWidgets.QPushButton(self.centralwidget)
        self.OffGo.setEnabled(False)
        self.OffGo.setGeometry(QtCore.QRect(2130, 400, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.OffGo.setFont(font)
        self.OffGo.setText("")
        self.OffGo.setIcon(icon9)
        self.OffGo.setIconSize(QtCore.QSize(25, 25))
        self.OffGo.setFlat(True)
        self.OffGo.setObjectName("OffGo")
        self.PlayPosition = QtWidgets.QPushButton(self.centralwidget)
        self.PlayPosition.setGeometry(QtCore.QRect(2050, 400, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.PlayPosition.setFont(font)
        self.PlayPosition.setText("")
        self.PlayPosition.setIcon(icon8)
        self.PlayPosition.setIconSize(QtCore.QSize(70, 70))
        self.PlayPosition.setCheckable(True)
        self.PlayPosition.setFlat(True)
        self.PlayPosition.setObjectName("PlayPosition")
        self.GoLabel = QtWidgets.QLabel(self.centralwidget)
        self.GoLabel.setGeometry(QtCore.QRect(2080, 480, 31, 21))
        self.GoLabel.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.GoLabel.setObjectName("GoLabel")
        self.CameraLogo = QtWidgets.QLabel(self.centralwidget)
        self.CameraLogo.setGeometry(QtCore.QRect(1030, 140, 131, 131))
        self.CameraLogo.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.CameraLogo.setText("")
        self.CameraLogo.setPixmap(QtGui.QPixmap("../../../../../../root/.designer/backup/Images/camera.png"))
        self.CameraLogo.setScaledContents(True)
        self.CameraLogo.setObjectName("CameraLogo")
        self.OnRobot1 = QtWidgets.QPushButton(self.centralwidget)
        self.OnRobot1.setEnabled(False)
        self.OnRobot1.setGeometry(QtCore.QRect(760, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.OnRobot1.setFont(font)
        self.OnRobot1.setText("")
        self.OnRobot1.setIcon(icon9)
        self.OnRobot1.setIconSize(QtCore.QSize(25, 25))
        self.OnRobot1.setFlat(True)
        self.OnRobot1.setObjectName("OnRobot1")
        self.OffRobot1 = QtWidgets.QPushButton(self.centralwidget)
        self.OffRobot1.setEnabled(False)
        self.OffRobot1.setGeometry(QtCore.QRect(1600, 60, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.OffRobot1.setFont(font)
        self.OffRobot1.setText("")
        self.OffRobot1.setIcon(icon9)
        self.OffRobot1.setIconSize(QtCore.QSize(25, 25))
        self.OffRobot1.setFlat(True)
        self.OffRobot1.setObjectName("OffRobot1")
        self.ScriptBox_3 = QtWidgets.QLabel(self.centralwidget)
        self.ScriptBox_3.setGeometry(QtCore.QRect(1820, 1000, 361, 321))
        self.ScriptBox_3.setStyleSheet("background-color:rgb(228, 228, 228)")
        self.ScriptBox_3.setObjectName("ScriptBox_3")
        self.CameraScreen_2 = QtWidgets.QPushButton(self.centralwidget)
        self.CameraScreen_2.setGeometry(QtCore.QRect(50, 854, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.CameraScreen_2.setFont(font)
        self.CameraScreen_2.setText("")
        self.CameraScreen_2.setIcon(icon7)
        self.CameraScreen_2.setIconSize(QtCore.QSize(70, 70))
        self.CameraScreen_2.setFlat(True)
        self.CameraScreen_2.setObjectName("CameraScreen_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(380, 400, 1301, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(300)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pick_and_place_robot_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.pick_and_place_robot_image.setMaximumSize(QtCore.QSize(300, 400))
        self.pick_and_place_robot_image.setText("")
        self.pick_and_place_robot_image.setPixmap(QtGui.QPixmap("airpick.jpg"))
        self.pick_and_place_robot_image.setScaledContents(True)
        self.pick_and_place_robot_image.setIndent(-4)
        self.pick_and_place_robot_image.setObjectName("pick_and_place_robot_image")
        self.horizontalLayout_2.addWidget(self.pick_and_place_robot_image)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
    

















        self.StartRobot_pp_2 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.power_on_robot(robot_name=''))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.StartRobot_pp_2.setFont(font)
        self.StartRobot_pp_2.setObjectName("StartRobot_pp_2")
        self.verticalLayout_4.addWidget(self.StartRobot_pp_2)
        # --------------------------- when clicked, emits an argument clicked() that indicates the state of the button. State can be pressed, released, toggle.. -----------
        self.LoadProgram_2 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.load_program_window())
        # self.LoadProgram_2 = QtWidgets.QPushButton(self.gridLayoutWidget)


        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoadProgram_2.setFont(font)
        self.LoadProgram_2.setObjectName("LoadProgram_2")
        self.verticalLayout_4.addWidget(self.LoadProgram_2)
        self.Play_pp_3 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.play_robot(robot_name=''))
        
        # if self.Play_pp_3.isChecked:
        #     print('clicked')
            # self.Play_pp_3.setStyleSheet("background-color: rgb(73, 221, 0);")
      
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Play_pp_3.setFont(font)
        self.Play_pp_3.setObjectName("Play_pp_3")
        self.verticalLayout_4.addWidget(self.Play_pp_3)
        self.Pause_pp_2 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.pause_program(robot_name=''))


        font = QtGui.QFont()
        font.setPointSize(11)
        self.Pause_pp_2.setFont(font)
        self.Pause_pp_2.setObjectName("Pause_pp_2")
        self.verticalLayout_4.addWidget(self.Pause_pp_2)
        self.Stop_pp_2 = QtWidgets.QPushButton(self.gridLayoutWidget, clicked = lambda: self.stop_program(robot_name=''))



        font = QtGui.QFont()
        font.setPointSize(11)
        self.Stop_pp_2.setFont(font)
        self.Stop_pp_2.setObjectName("Stop_pp_2")
        self.verticalLayout_4.addWidget(self.Stop_pp_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dispense_robot_image = QtWidgets.QLabel(self.gridLayoutWidget)
        self.dispense_robot_image.setMaximumSize(QtCore.QSize(300, 400))
        self.dispense_robot_image.setText("")
        self.dispense_robot_image.setPixmap(QtGui.QPixmap("dispensepng.png"))
        self.dispense_robot_image.setScaledContents(True)
        self.dispense_robot_image.setIndent(-4)
        self.dispense_robot_image.setObjectName("dispense_robot_image")
        self.horizontalLayout_7.addWidget(self.dispense_robot_image)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.StartRobot_pp_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.StartRobot_pp_3.setFont(font)
        self.StartRobot_pp_3.setObjectName("StartRobot_pp_3")
        self.verticalLayout_6.addWidget(self.StartRobot_pp_3)
        self.LoadProgram_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.LoadProgram_3.setFont(font)
        self.LoadProgram_3.setObjectName("LoadProgram_3")
        self.verticalLayout_6.addWidget(self.LoadProgram_3)
        self.Play_pp_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Play_pp_4.setFont(font)
        self.Play_pp_4.setObjectName("Play_pp_4")
        self.verticalLayout_6.addWidget(self.Play_pp_4)
        self.Pause_pp_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Pause_pp_3.setFont(font)
        self.Pause_pp_3.setObjectName("Pause_pp_3")
        self.verticalLayout_6.addWidget(self.Pause_pp_3)
        self.Stop_pp_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Stop_pp_3.setFont(font)
        self.Stop_pp_3.setObjectName("Stop_pp_3")
        self.verticalLayout_6.addWidget(self.Stop_pp_3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 1, 1, 1)
        self.Button_Bar.raise_()
        self.OutputBox.raise_()
        self.ScriptBox_2.raise_()
        self.PositionBox.raise_()
        self.Top_Bar.raise_()
        self.SkyshipsLogo.raise_()
        self.LoadScript.raise_()
        self.Settings.raise_()
        self.Help.raise_()
        self.Robot2Connect.raise_()
        self.TaskBox.raise_()
        self.Script_Output.raise_()
        self.ScriptOutput.raise_()
        self.TaskLabel.raise_()
        self.Positions_2.raise_()
        self.Emergency.raise_()
        self.ScriptBox.raise_()
        self.Connected1.raise_()
        self.Connected2.raise_()
        self.UpPosition.raise_()
        self.SidePosition.raise_()
        self.progressBar.raise_()
        self.dial.raise_()
        self.YBox.raise_()
        self.XAxis.raise_()
        self.DisconnectedCamera.raise_()
        self.Robot1Connect.raise_()
        self.CameraConnect.raise_()
        self.Back2.raise_()
        self.Pause1.raise_()
        self.Play1.raise_()
        self.Restart1.raise_()
        self.Back1.raise_()
        self.Restart2.raise_()
        self.Pause2.raise_()
        self.Play2.raise_()
        self.ZBox.raise_()
        self.XBox.raise_()
        self.YAxis.raise_()
        self.ZAxis.raise_()
        self.XAxis_2.raise_()
        self.YAxis_2.raise_()
        self.TaskBox_2.raise_()
        self.CameraOutput.raise_()
        self.CameraTitle.raise_()
        self.thermal.raise_()
        self.Assembly.raise_()
        self.ThermalPaste.raise_()
        self.Assembly_2.raise_()
        self.Off2.raise_()
        self.Off1.raise_()
        self.Dissemble.raise_()
        self.Off3.raise_()
        self.Off4.raise_()
        self.CameraCheck.raise_()
        self.CameraCheck_2.raise_()
        self.Dissemble_2.raise_()
        self.ScrewOut.raise_()
        self.On5.raise_()
        self.Off6.raise_()
        self.Empty9_2.raise_()
        self.ScrewIn.raise_()
        self.LoadedScript.raise_()
        self.ScrewIn_2.raise_()
        self.LoadedScript_2.raise_()
        self.Off16.raise_()
        self.Off8.raise_()
        self.Empty9.raise_()
        self.ScrewOut_2.raise_()
        self.Off10.raise_()
        self.Empty8_2.raise_()
        self.Off12.raise_()
        self.Off13.raise_()
        self.Empty7.raise_()
        self.SwapRobot_2.raise_()
        self.Empty4.raise_()
        self.Empty6_2.raise_()
        self.CameraScreen.raise_()
        self.Empty3_2.raise_()
        self.Off15.raise_()
        self.Empty3.raise_()
        self.Empty5.raise_()
        self.Empty8.raise_()
        self.Empty5_2.raise_()
        self.Off14.raise_()
        self.Empty7_2.raise_()
        self.Empty4_2.raise_()
        self.Off7.raise_()
        self.Empty6.raise_()
        self.Off9.raise_()
        self.SwapRobot.raise_()
        self.OffGo.raise_()
        self.PlayPosition.raise_()
        self.GoLabel.raise_()
        self.CameraLogo.raise_()
        self.OnRobot1.raise_()
        self.OffRobot1.raise_()
        self.ScriptBox_3.raise_()
        self.CameraScreen_2.raise_()
        self.Off11.raise_()
        self.gridLayoutWidget.raise_()
        RobotControl.setCentralWidget(self.centralwidget)

        self.retranslateUi(RobotControl)
        QtCore.QMetaObject.connectSlotsByName(RobotControl)

    def retranslateUi(self, RobotControl):
        _translate = QtCore.QCoreApplication.translate
        RobotControl.setWindowTitle(_translate("RobotControl", "Robot Control"))
        self.Top_Bar.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.Top_Bar.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.LoadScript.setText(_translate("RobotControl", "Load Script"))
        self.Settings.setText(_translate("RobotControl", "Settings"))
        self.Help.setText(_translate("RobotControl", "Help"))
        self.Button_Bar.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.Button_Bar.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.TaskBox.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.TaskBox.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.Script_Output.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.Script_Output.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.ScriptOutput.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Script Output</span></p></body></html>"))
        self.TaskLabel.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Tasks</span></p></body></html>"))
        self.Positions_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Positions</span></p></body></html>"))
        self.ScriptBox_2.setToolTip(_translate("RobotControl", "<html><head/><body><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test1</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test2</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test3</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test4</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test5</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test6</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test7</span></a></p></body></html>"))
        self.ScriptBox_2.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test1</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test2</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test3</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test4</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test5</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test6</span></a></p><p><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Test7</span></a></p></body></html>"))
        self.ScriptBox_2.setHtml(_translate("RobotControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Sans Serif\'; font-size:14pt; font-weight:600; text-decoration: underline;\">Recent Scripts</span></p></body></html>"))
        self.OutputBox.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.OutputBox.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.ScriptBox.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.ScriptBox.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.Connected1.setText(_translate("RobotControl", "Robot 1 - Connected"))
        self.Connected2.setText(_translate("RobotControl", "Robot 2 - Connected"))
        self.YBox.setHtml(_translate("RobotControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.XAxis.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:11pt;\">X:</span></p></body></html>"))
        self.DisconnectedCamera.setToolTip(_translate("RobotControl", "<html><head/><body><p>Camera - Disconnected</p></body></html>"))
        self.DisconnectedCamera.setText(_translate("RobotControl", "Camera - Disconnected"))
        self.ZBox.setHtml(_translate("RobotControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.XBox.setHtml(_translate("RobotControl", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8pt;\"><br /></p></body></html>"))
        self.YAxis.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:11pt;\">Y:</span></p></body></html>"))
        self.ZAxis.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:11pt;\">Z:</span></p></body></html>"))
        self.XAxis_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:11pt;\">X:</span></p></body></html>"))
        self.YAxis_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:11pt;\">Y:</span></p></body></html>"))
        self.PositionBox.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.PositionBox.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.TaskBox_2.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.TaskBox_2.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.CameraOutput.setToolTip(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.CameraOutput.setWhatsThis(_translate("RobotControl", "<html><head/><body><p><img src=\":/Photo/logo.png\"/></p></body></html>"))
        self.CameraTitle.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; text-decoration: underline;\">Camera Output</span></p></body></html>"))
        self.ThermalPaste.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Thermal Paste</span></p></body></html>"))
        self.Assembly_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Assembly</span></p></body></html>"))
        self.CameraCheck_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Camera Check</span></p></body></html>"))
        self.Dissemble_2.setText(_translate("RobotControl", "<html><head/><body><p>Dissemble</p></body></html>"))
        self.Empty9_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.LoadedScript.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Loaded Script</span></p><p><br/></p></body></html>"))
        self.ScrewIn_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Screw In</span></p></body></html>"))
        self.ScrewOut_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Screw out</span></p></body></html>"))
        self.Empty8_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.SwapRobot_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Swap Robot </span></p></body></html>"))
        self.Empty6_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.CameraScreen.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Camera </span></p><p><span style=\" font-size:10pt;\">MainScreen</span></p></body></html>"))
        self.Empty3_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.Empty5_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.Empty7_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.Empty4_2.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:10pt;\">Empty</span></p></body></html>"))
        self.GoLabel.setText(_translate("RobotControl", "<html><head/><body><p><span style=\" font-size:12pt;\">Go </span></p></body></html>"))
        self.ScriptBox_3.setText(_translate("RobotControl", "<html><head/><body><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/Assemble.py</span></a></p><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/ScrewIn.py</span></a></p><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/ScrewOut.py</span></a></p><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/CameraCheck.py</span></a></p><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/ThermalPaste.py</span></a></p><p align=\"center\"><a href=\"www.google.com\"><span style=\" text-decoration: underline; color:#0000ff;\">Documents/Dissamble.py</span></a></p></body></html>"))
        self.StartRobot_pp_2.setText(_translate("RobotControl", "Start Robot"))
        self.LoadProgram_2.setText(_translate("RobotControl", "Load Program"))
        self.Play_pp_3.setText(_translate("RobotControl", "Play Program"))
        self.Pause_pp_2.setText(_translate("RobotControl", "Pause Program"))
        self.Stop_pp_2.setText(_translate("RobotControl", "Stop Program"))
        self.StartRobot_pp_3.setText(_translate("RobotControl", "Start Robot"))
        self.LoadProgram_3.setText(_translate("RobotControl", "Load Program"))
        self.Play_pp_4.setText(_translate("RobotControl", "Play Program"))
        self.Pause_pp_3.setText(_translate("RobotControl", "Pause Program"))
        self.Stop_pp_3.setText(_translate("RobotControl", "Stop Program"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RobotControl = QtWidgets.QMainWindow()

    ui = Ui_RobotControl()
    ui.setupUi(RobotControl)
    RobotControl.show()
    sys.exit(app.exec_())

